//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XebiaLabs.Deployit.UI.Properties {
    using System;
    
    
    //? <summary>
    //?   A strongly-typed resource class, for looking up localized strings, etc.
    //? </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        //? <summary>
        //?   Returns the cached ResourceManager instance used by this class.
        //? </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XebiaLabs.Deployit.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        //? <summary>
        //?   Overrides the current thread's CurrentUICulture property for all
        //?   resource lookups using this strongly typed resource class.
        //? </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to New.
        //? </summary>
        internal static string EDITOR_NEW_CI {
            get {
                return ResourceManager.GetString("EDITOR_NEW_CI", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to false.
        //? </summary>
        internal static string PROPERTY_BOOL_FALSE {
            get {
                return ResourceManager.GetString("PROPERTY_BOOL_FALSE", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to not defined.
        //? </summary>
        internal static string PROPERTY_BOOL_ND {
            get {
                return ResourceManager.GetString("PROPERTY_BOOL_ND", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to true.
        //? </summary>
        internal static string PROPERTY_BOOL_TRUE {
            get {
                return ResourceManager.GetString("PROPERTY_BOOL_TRUE", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to This is a boolean property.
        //? </summary>
        internal static string PROPERTY_BOOLREQUIRED {
            get {
                return ResourceManager.GetString("PROPERTY_BOOLREQUIRED", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to not defined.
        //? </summary>
        internal static string PROPERTY_ENUM_ND {
            get {
                return ResourceManager.GetString("PROPERTY_ENUM_ND", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to This is an integer property.
        //? </summary>
        internal static string PROPERTY_INTREQUIRED {
            get {
                return ResourceManager.GetString("PROPERTY_INTREQUIRED", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to Required.
        //? </summary>
        internal static string PROPERTY_REQUIRED {
            get {
                return ResourceManager.GetString("PROPERTY_REQUIRED", resourceCulture);
            }
        }
        
        //? <summary>
        //?   Looks up a localized string similar to A set requires unique values.
        //? </summary>
        internal static string PROPERTY_SETOFSTRING_UNIQUEVALUES {
            get {
                return ResourceManager.GetString("PROPERTY_SETOFSTRING_UNIQUEVALUES", resourceCulture);
            }
        }
    }
}
